// GENERATED by scripts/generate-migrations.mjs — do not edit by hand.
// Run `pnpm generate:migrations` after changing anything under packages/db/migrations.
//
// The SQL lives here as well as in the .sql files so applying migrations never depends
// on a filesystem path. A path relative to the module works only when running from the
// source tree; bundled or containerised it points elsewhere and the process dies on
// start — which no test can catch, because tests always run from the source tree.

export type Migration = { name: string; sql: string }

export const MIGRATIONS: Migration[] = [
  {
    name: "0001_init.sql",
    sql: `CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE tenants (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        text NOT NULL UNIQUE,
  name        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_settings (
  tenant_id                       uuid PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  chat_model                      text NOT NULL DEFAULT 'claude-opus-5',
  rewrite_model                   text NOT NULL DEFAULT 'claude-opus-5',
  embedding_model                 text NOT NULL DEFAULT 'text-embedding-3-small',
  refusal_text                    text NOT NULL DEFAULT 'Sorry, I do not have that information yet. May I connect you with our team?',
  escalation_mode                 text NOT NULL DEFAULT 'collect_contact',
  escalation_target               text,
  monthly_budget_cents            integer NOT NULL DEFAULT 0,
  retention_days                  integer NOT NULL DEFAULT 90,
  high_risk_topics                text[] NOT NULL DEFAULT ARRAY['price','discount','warranty','refund','stock','legal'],
  allowed_origins                 text[] NOT NULL DEFAULT ARRAY[]::text[],
  widget_theme                    jsonb NOT NULL DEFAULT '{}'::jsonb,
  max_handoffs_per_turn           integer NOT NULL DEFAULT 2,
  max_handoffs_per_conversation   integer NOT NULL DEFAULT 5
);

CREATE TABLE admin_users (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id      uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  email          text NOT NULL,
  password_hash  text NOT NULL,
  role           text NOT NULL DEFAULT 'owner',
  oauth_provider text,
  oauth_subject  text,
  UNIQUE (tenant_id, email),
  UNIQUE (tenant_id, id)
);

CREATE TABLE admin_sessions (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  admin_user_id uuid NOT NULL,
  expires_at    timestamptz NOT NULL,
  FOREIGN KEY (tenant_id, admin_user_id) REFERENCES admin_users(tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE knowledge_sources (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  kind            text NOT NULL CHECK (kind IN ('url','file','text')),
  uri             text NOT NULL,
  status          text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','indexing','ready','error')),
  last_indexed_at timestamptz,
  error           text,
  UNIQUE (tenant_id, id)
);

CREATE TABLE documents (
  id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  source_id uuid NOT NULL,
  title     text NOT NULL,
  url       text,
  FOREIGN KEY (tenant_id, source_id) REFERENCES knowledge_sources(tenant_id, id) ON DELETE CASCADE,
  UNIQUE (tenant_id, id)
);

CREATE TABLE chunks (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  document_id     uuid NOT NULL,
  ordinal         integer NOT NULL,
  content         text NOT NULL,
  embedding       vector(1536),
  embedding_model text NOT NULL,
  tsv             tsvector GENERATED ALWAYS AS (to_tsvector('simple', content)) STORED,
  FOREIGN KEY (tenant_id, document_id) REFERENCES documents(tenant_id, id) ON DELETE CASCADE,
  UNIQUE (tenant_id, id)
);

CREATE INDEX chunks_tenant_idx ON chunks (tenant_id);
CREATE INDEX chunks_tsv_idx    ON chunks USING GIN (tsv);
CREATE INDEX chunks_embed_idx  ON chunks USING hnsw (embedding vector_cosine_ops);

CREATE TABLE conversations (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  channel       text NOT NULL,
  visitor_id    text NOT NULL,
  handoff_count integer NOT NULL DEFAULT 0,
  status        text NOT NULL DEFAULT 'active'
                CHECK (status IN ('active','idle','escalated','closed')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id)
);

CREATE TABLE messages (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id uuid NOT NULL,
  role            text NOT NULL CHECK (role IN ('user','assistant')),
  content         text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, conversation_id) REFERENCES conversations(tenant_id, id) ON DELETE CASCADE,
  UNIQUE (tenant_id, id)
);

CREATE TABLE message_citations (
  tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  message_id uuid NOT NULL,
  chunk_id   uuid NOT NULL,
  PRIMARY KEY (message_id, chunk_id),
  FOREIGN KEY (tenant_id, message_id) REFERENCES messages(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, chunk_id) REFERENCES chunks(tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE escalations (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id uuid NOT NULL,
  reason          text NOT NULL CHECK (reason IN (
                    'no_source','ungrounded','budget_exhausted',
                    'provider_unavailable','schema_invalid',
                    'handoff_limit','visitor_request')),
  resolved_at     timestamptz,
  FOREIGN KEY (tenant_id, conversation_id) REFERENCES conversations(tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE usage_events (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  model         text NOT NULL,
  input_tokens  integer NOT NULL,
  output_tokens integer NOT NULL,
  cached_tokens integer,
  cost_cents    integer NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Application role. Not a superuser, not a table owner, so RLS applies.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'quidchat_app') THEN
    CREATE ROLE quidchat_app NOLOGIN;
  END IF;
END $$;

GRANT USAGE ON SCHEMA public TO quidchat_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO quidchat_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO quidchat_app;

-- The application role may only READ its own row in \`tenants\`, nothing more.
-- The \`GRANT ... ON ALL TABLES\` above also gives it UPDATE and DELETE, and both are
-- dangerous: \`DELETE FROM tenants\` inside withTenant succeeded and cascaded away all
-- of that tenant's own data; \`UPDATE tenants SET slug=...\` succeeded, and because the
-- unique index on slug is GLOBAL it becomes a cross-tenant existence oracle — a slug
-- belonging to another tenant raises a duplicate key, a free slug succeeds.
--
-- Onboarding does use the raw handle, because the \`tenant_self\` policy makes an INSERT
-- as quidchat_app impossible to succeed. So nothing is lost.
REVOKE INSERT, UPDATE, DELETE ON tenants FROM quidchat_app;

-- The role the application uses to connect MUST be a member of \`quidchat_app\`, or
-- \`SET LOCAL ROLE quidchat_app\` in withTenant() fails with "permission denied to set
-- role". \`quidchat_app\` itself is NOLOGIN by design: it is not a role to connect as, it
-- is a role to be DEMOTED INTO after connecting. This line grants that membership to
-- the role currently running the migration, which on tier 1 and 2 is the application
-- role.
DO $grant$
BEGIN
  BEGIN
    EXECUTE format('GRANT quidchat_app TO %I', current_user);
  EXCEPTION
    WHEN insufficient_privilege THEN NULL;  -- may already be a member via another path
  END;
  -- Proof, not hope: if this role cannot be demoted into quidchat_app, EVERY request
  -- will fail in withTenant() — far better to fail here.
  BEGIN
    EXECUTE 'SET LOCAL ROLE quidchat_app';
    EXECUTE 'RESET ROLE';
  EXCEPTION WHEN OTHERS THEN
    RAISE EXCEPTION
      'role % cannot SET ROLE quidchat_app. Run as superuser: GRANT quidchat_app TO %',
      current_user, current_user;
  END;
END $grant$;

-- Helper: the current transaction's tenant context.
CREATE OR REPLACE FUNCTION current_tenant_id() RETURNS uuid
LANGUAGE sql STABLE
SET search_path = pg_catalog, public
AS $$
  SELECT NULLIF(current_setting('quidchat.tenant_id', true), '')::uuid
$$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'tenant_settings','admin_users','knowledge_sources','documents','chunks',
    'conversations','messages','message_citations','escalations','admin_sessions','usage_events'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING (tenant_id = current_tenant_id()) '
      || 'WITH CHECK (tenant_id = current_tenant_id())', t);
  END LOOP;
END $$;

-- tenants itself: read via id, not tenant_id.
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_self ON tenants USING (id = current_tenant_id());

-- message_citations and admin_sessions: the composite FK guarantees tenant_id matches
-- the parent. Both of their parent references are now composite and cannot cross tenants.

-- Tenant isolation guard. ONE block, enumerating via RLS.
--
-- An earlier version selected tables via \`column_name = 'tenant_id'\`, and THAT was
-- the mistake: \`tenants\` keys on \`id\`, so it escaped every layer of defence at once.
-- Leaking its policy made \`SELECT slug FROM tenants\` return the entire customer
-- list, and not a single test failed.
--
-- An earlier version also only inspected \`qual\`, which is the READ path. \`WITH CHECK
-- (true)\` opened the WRITE path completely: measured against PGlite, a usage_events
-- row worth 500,000 cents could be written to another tenant's ledger, and a
-- fabricated assistant message could be planted in another business's transcript.
-- The guard stayed silent, and 44 tests remained green.
--
-- \`with_check IS NULL\` is legitimate and means Postgres derives it from \`qual\` —
-- that's what happens for \`tenants\`. What is rejected is a \`with_check\` that IS
-- present but differs.
DO $guard_isolation$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s: %s', t.name, a.reason), ' | ') INTO bad
  FROM (
    SELECT c.relname AS name,
           n.nspname AS schema,
           -- This table's tenant key: \`tenant_id\` if it exists, otherwise \`id\`.
           -- \`tenants\` uses \`id\` because it IS the tenant itself.
           CASE WHEN EXISTS (
             SELECT 1 FROM information_schema.columns col
             WHERE col.table_schema = n.nspname AND col.table_name = c.relname
               AND col.column_name = 'tenant_id'
           ) THEN 'tenant_id' ELSE 'id' END AS key,
           c.relrowsecurity AS rls_enabled,
           c.relforcerowsecurity AS rls_forced
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
      AND n.nspname NOT LIKE 'pg_temp%'
      AND n.nspname NOT LIKE 'pg_toast_temp%'
      AND c.relkind IN ('r', 'p')   -- 'p' = partitioned table; its parent is NOT 'r'
      -- Infrastructure tables are named with a leading underscore and hold no tenant
      -- data. The migration ledger is one: it must exist before the first migration
      -- runs, so it cannot be created by a migration that this guard then inspects.
      --
      -- This is a stated rule rather than a list of exempt names, and the rule cannot be
      -- abused to hide tenant data: \`isolation-guard.test.ts\` asserts that no table
      -- whose name starts with an underscore has a \`tenant_id\` column, so smuggling
      -- tenant-scoped data behind the prefix fails a test.
      AND c.relname NOT LIKE '\\_%'
  ) t
  CROSS JOIN LATERAL (
    SELECT format('(%s = current_tenant_id())', t.key) AS expected
  ) h
  CROSS JOIN LATERAL (
    SELECT
      CASE
        WHEN NOT (t.rls_enabled AND t.rls_forced) THEN 'RLS not enabled or not forced'
        WHEN NOT EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
        ) THEN 'no policy'
        WHEN EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND p.qual IS NOT NULL AND p.qual <> h.expected
        ) THEN format('has a permissive policy with qual other than %s', h.expected)
        WHEN EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND p.with_check IS NOT NULL AND p.with_check <> h.expected
        ) THEN format('has a permissive policy with with_check other than %s', h.expected)
        WHEN NOT EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND (p.qual = h.expected OR p.with_check = h.expected)
        ) THEN 'no permissive policy scopes to the tenant'
      END AS reason
  ) a
  WHERE a.reason IS NOT NULL;

  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'tenant isolation incomplete -> %', bad;
  END IF;
END $guard_isolation$;

-- Views and matviews do NOT have RLS of their own. A view runs with its OWNER's
-- privileges unless created \`WITH (security_invoker = true)\`, and that default is
-- OFF. Measured: a plain view over \`conversations\` made tenant A see tenant B's
-- messages.
--
-- Matviews are worse: \`security_invoker\` does not apply to them at all, so the only
-- safe posture is withholding SELECT from the application role.
DO $guard_view$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, c.relname), ', ') INTO bad
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'v'
    AND has_table_privilege('quidchat_app', c.oid, 'SELECT')
    AND NOT coalesce(
      (SELECT option_value = 'true' FROM pg_options_to_table(c.reloptions)
       WHERE option_name = 'security_invoker'), false);
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'view without security_invoker=true but readable by quidchat_app -> %; the caller''s RLS does NOT apply there',
      bad;
  END IF;
END $guard_view$;

DO $guard_matview$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, c.relname), ', ') INTO bad
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'm'
    AND has_table_privilege('quidchat_app', c.oid, 'SELECT');
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'materialized view readable by quidchat_app -> %; matviews do not support security_invoker, so its SELECT privilege must be revoked',
      bad;
  END IF;
END $guard_matview$;

-- SECURITY DEFINER functions run as their creator, so they bypass RLS. And \`EXECUTE\`
-- is granted to PUBLIC by DEFAULT — without any explicit GRANT, the application role
-- can already call one. Measured: a dashboard function returned both tenants' message
-- counts.
--
-- \`current_tenant_id()\` itself is exempted: it genuinely needs to exist and it is
-- INVOKER.
DO $guard_secdef$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, p.proname), ', ') INTO bad
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND p.prosecdef
    AND has_function_privilege('quidchat_app', p.oid, 'EXECUTE');
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'SECURITY DEFINER function executable by quidchat_app -> %; such functions bypass RLS',
      bad;
  END IF;
END $guard_secdef$;
`,
  },
  {
    name: "0002_skills.sql",
    sql: `-- Multi-skill routing: one skill = a persona + a subset of knowledge, selected by an
-- ordered list of routing rules (spec §5).

CREATE TABLE skills (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name          text NOT NULL,
  description   text,
  system_prompt text,
  enabled       boolean NOT NULL DEFAULT true,
  is_fallback   boolean NOT NULL DEFAULT false,
  -- NULL means "inherit from tenant_settings" — the same pattern already used by
  -- \`skills.escalation_mode\` in the design doc.
  answer_mode   text CHECK (answer_mode IN ('static', 'thrifty', 'full')),
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id)
);

-- Knowledge scoping: which sources a skill may retrieve from. This is the SECOND
-- isolation boundary (spec §3.5) — RLS keeps tenants apart, this keeps skills apart
-- within one tenant. No own \`id\`/\`tenant_id\` role beyond the FK guard, same shape as
-- \`message_citations\` in 0001_init.sql: both composite FKs pin \`tenant_id\` so a row
-- can never link a skill and a source that belong to different tenants.
CREATE TABLE skill_sources (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  skill_id  uuid NOT NULL,
  source_id uuid NOT NULL,
  PRIMARY KEY (skill_id, source_id),
  FOREIGN KEY (tenant_id, skill_id) REFERENCES skills(tenant_id, id) ON DELETE CASCADE,
  FOREIGN KEY (tenant_id, source_id) REFERENCES knowledge_sources(tenant_id, id) ON DELETE CASCADE
);

CREATE TABLE routing_rules (
  id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  skill_id  uuid NOT NULL,
  position  integer NOT NULL,
  kind      text NOT NULL CHECK (kind IN ('keyword', 'semantic', 'llm', 'fallback')),
  pattern   text,
  enabled   boolean NOT NULL DEFAULT true,
  FOREIGN KEY (tenant_id, skill_id) REFERENCES skills(tenant_id, id) ON DELETE CASCADE,
  UNIQUE (tenant_id, id)
);

CREATE INDEX routing_rules_tenant_position_idx ON routing_rules (tenant_id, position);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['skills', 'skill_sources', 'routing_rules'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY tenant_isolation ON %I USING (tenant_id = current_tenant_id()) '
      || 'WITH CHECK (tenant_id = current_tenant_id())', t);
  END LOOP;
END $$;

-- Tenant isolation guard, copied VERBATIM from the end of 0001_init.sql.
--
-- The guard in 0001 enumerates every RLS-relevant object AT THE TIME IT RAN — it ran
-- before \`skills\`, \`skill_sources\`, and \`routing_rules\` existed, so it never checked
-- them. Re-running the identical guard here, after those tables are created, is the
-- whole point: it re-enumerates the database as it stands NOW, so the new tables get
-- the exact same scrutiny the original ones got. If a future migration adds a table
-- and forgets RLS, this copy — or whichever migration runs last at the time — is what
-- catches it.
DO $guard_isolation$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s: %s', t.name, a.reason), ' | ') INTO bad
  FROM (
    SELECT c.relname AS name,
           n.nspname AS schema,
           -- This table's tenant key: \`tenant_id\` if it exists, otherwise \`id\`.
           -- \`tenants\` uses \`id\` because it IS the tenant itself.
           CASE WHEN EXISTS (
             SELECT 1 FROM information_schema.columns col
             WHERE col.table_schema = n.nspname AND col.table_name = c.relname
               AND col.column_name = 'tenant_id'
           ) THEN 'tenant_id' ELSE 'id' END AS key,
           c.relrowsecurity AS rls_enabled,
           c.relforcerowsecurity AS rls_forced
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
      AND n.nspname NOT LIKE 'pg_temp%'
      AND n.nspname NOT LIKE 'pg_toast_temp%'
      AND c.relkind IN ('r', 'p')   -- 'p' = partitioned table; its parent is NOT 'r'
      -- Infrastructure tables are named with a leading underscore and hold no tenant
      -- data. The migration ledger is one: it must exist before the first migration
      -- runs, so it cannot be created by a migration that this guard then inspects.
      --
      -- This is a stated rule rather than a list of exempt names, and the rule cannot be
      -- abused to hide tenant data: \`isolation-guard.test.ts\` asserts that no table
      -- whose name starts with an underscore has a \`tenant_id\` column, so smuggling
      -- tenant-scoped data behind the prefix fails a test.
      AND c.relname NOT LIKE '\\_%'
  ) t
  CROSS JOIN LATERAL (
    SELECT format('(%s = current_tenant_id())', t.key) AS expected
  ) h
  CROSS JOIN LATERAL (
    SELECT
      CASE
        WHEN NOT (t.rls_enabled AND t.rls_forced) THEN 'RLS not enabled or not forced'
        WHEN NOT EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
        ) THEN 'no policy'
        WHEN EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND p.qual IS NOT NULL AND p.qual <> h.expected
        ) THEN format('has a permissive policy with qual other than %s', h.expected)
        WHEN EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND p.with_check IS NOT NULL AND p.with_check <> h.expected
        ) THEN format('has a permissive policy with with_check other than %s', h.expected)
        WHEN NOT EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND (p.qual = h.expected OR p.with_check = h.expected)
        ) THEN 'no permissive policy scopes to the tenant'
      END AS reason
  ) a
  WHERE a.reason IS NOT NULL;

  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'tenant isolation incomplete -> %', bad;
  END IF;
END $guard_isolation$;

-- Views and matviews do NOT have RLS of their own. A view runs with its OWNER's
-- privileges unless created \`WITH (security_invoker = true)\`, and that default is
-- OFF. Measured: a plain view over \`conversations\` made tenant A see tenant B's
-- messages.
--
-- Matviews are worse: \`security_invoker\` does not apply to them at all, so the only
-- safe posture is withholding SELECT from the application role.
DO $guard_view$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, c.relname), ', ') INTO bad
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'v'
    AND has_table_privilege('quidchat_app', c.oid, 'SELECT')
    AND NOT coalesce(
      (SELECT option_value = 'true' FROM pg_options_to_table(c.reloptions)
       WHERE option_name = 'security_invoker'), false);
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'view without security_invoker=true but readable by quidchat_app -> %; the caller''s RLS does NOT apply there',
      bad;
  END IF;
END $guard_view$;

DO $guard_matview$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, c.relname), ', ') INTO bad
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'm'
    AND has_table_privilege('quidchat_app', c.oid, 'SELECT');
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'materialized view readable by quidchat_app -> %; matviews do not support security_invoker, so its SELECT privilege must be revoked',
      bad;
  END IF;
END $guard_matview$;

-- SECURITY DEFINER functions run as their creator, so they bypass RLS. And \`EXECUTE\`
-- is granted to PUBLIC by DEFAULT — without any explicit GRANT, the application role
-- can already call one. Measured: a dashboard function returned both tenants' message
-- counts.
--
-- \`current_tenant_id()\` itself is exempted: it genuinely needs to exist and it is
-- INVOKER.
DO $guard_secdef$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, p.proname), ', ') INTO bad
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND p.prosecdef
    AND has_function_privilege('quidchat_app', p.oid, 'EXECUTE');
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'SECURITY DEFINER function executable by quidchat_app -> %; such functions bypass RLS',
      bad;
  END IF;
END $guard_secdef$;
`,
  },
  {
    name: "0003_answer_modes.sql",
    sql: `-- Answer modes: \`static\` (canned text, zero LLM cost at runtime), \`thrifty\`
-- (local embedding, still no generation), \`full\` (today's pipeline, unchanged).
-- See docs/superpowers/specs/2026-07-29-quidchat-kernel-design.md §6.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE tenant_settings
  ADD COLUMN answer_mode text NOT NULL DEFAULT 'full'
    CHECK (answer_mode IN ('static', 'thrifty', 'full'));

-- \`canned_answers\` is \`static\` mode's only data source. Nothing here reaches a
-- customer until a human sets \`status = 'approved'\` — an AI-proposed row
-- starts at \`draft\` and is invisible to matching until then. That's what makes
-- \`static\` mode trustworthy for price/warranty questions: every live answer
-- was read by a person before it could ever be sent.
CREATE TABLE canned_answers (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  question   text NOT NULL,
  answer     text NOT NULL,
  status     text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'approved')),
  created_at timestamptz NOT NULL DEFAULT now(),
  -- Mirrors \`chunks.tsv\` above: a generated column, deliberately kept out of
  -- the Drizzle model (see the note on \`chunks\` in schema.ts) because it's
  -- only ever read through raw SQL in \`matchCannedAnswer\`.
  tsv        tsvector GENERATED ALWAYS AS (to_tsvector('simple', question)) STORED,
  UNIQUE (tenant_id, id)
);

CREATE INDEX canned_answers_tenant_idx         ON canned_answers (tenant_id);
CREATE INDEX canned_answers_tsv_idx            ON canned_answers USING GIN (tsv);
-- Trigram index so a near-miss (typo, reordered words) still matches when
-- full-text search finds nothing.
CREATE INDEX canned_answers_question_trgm_idx  ON canned_answers USING GIN (question gin_trgm_ops);

ALTER TABLE canned_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE canned_answers FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON canned_answers
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());

-- Tenant isolation guard, copied verbatim from the end of 0001_init.sql so
-- \`canned_answers\` is proven by the same check every other tenant-scoped table
-- already passes, rather than trusted on inspection alone.
--
-- An earlier version selected tables via \`column_name = 'tenant_id'\`, and THAT
-- was the mistake: \`tenants\` keys on \`id\`, so it escaped every layer of
-- defence at once. Leaking its policy made \`SELECT slug FROM tenants\` return
-- the entire customer list, and not a single test failed.
--
-- An earlier version also only inspected \`qual\`, which is the READ path.
-- \`WITH CHECK (true)\` opened the WRITE path completely: measured against
-- PGlite, a usage_events row worth 500,000 cents could be written to another
-- tenant's ledger, and a fabricated assistant message could be planted in
-- another business's transcript. The guard stayed silent, and 44 tests
-- remained green.
--
-- \`with_check IS NULL\` is legitimate and means Postgres derives it from \`qual\`
-- — that's what happens for \`tenants\`. What is rejected is a \`with_check\` that
-- IS present but differs.
DO $guard_isolation$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s: %s', t.name, a.reason), ' | ') INTO bad
  FROM (
    SELECT c.relname AS name,
           n.nspname AS schema,
           -- This table's tenant key: \`tenant_id\` if it exists, otherwise \`id\`.
           -- \`tenants\` uses \`id\` because it IS the tenant itself.
           CASE WHEN EXISTS (
             SELECT 1 FROM information_schema.columns col
             WHERE col.table_schema = n.nspname AND col.table_name = c.relname
               AND col.column_name = 'tenant_id'
           ) THEN 'tenant_id' ELSE 'id' END AS key,
           c.relrowsecurity AS rls_enabled,
           c.relforcerowsecurity AS rls_forced
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast')
      AND n.nspname NOT LIKE 'pg_temp%'
      AND n.nspname NOT LIKE 'pg_toast_temp%'
      AND c.relkind IN ('r', 'p')   -- 'p' = partitioned table; its parent is NOT 'r'
      -- Infrastructure tables are named with a leading underscore and hold no tenant
      -- data. The migration ledger is one: it must exist before the first migration
      -- runs, so it cannot be created by a migration that this guard then inspects.
      --
      -- This is a stated rule rather than a list of exempt names, and the rule cannot be
      -- abused to hide tenant data: \`isolation-guard.test.ts\` asserts that no table
      -- whose name starts with an underscore has a \`tenant_id\` column, so smuggling
      -- tenant-scoped data behind the prefix fails a test.
      AND c.relname NOT LIKE '\\_%'
  ) t
  CROSS JOIN LATERAL (
    SELECT format('(%s = current_tenant_id())', t.key) AS expected
  ) h
  CROSS JOIN LATERAL (
    SELECT
      CASE
        WHEN NOT (t.rls_enabled AND t.rls_forced) THEN 'RLS not enabled or not forced'
        WHEN NOT EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
        ) THEN 'no policy'
        WHEN EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND p.qual IS NOT NULL AND p.qual <> h.expected
        ) THEN format('has a permissive policy with qual other than %s', h.expected)
        WHEN EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND p.with_check IS NOT NULL AND p.with_check <> h.expected
        ) THEN format('has a permissive policy with with_check other than %s', h.expected)
        WHEN NOT EXISTS (
          SELECT 1 FROM pg_policies p
          WHERE p.schemaname = t.schema AND p.tablename = t.name
            AND p.permissive = 'PERMISSIVE'
            AND (p.qual = h.expected OR p.with_check = h.expected)
        ) THEN 'no permissive policy scopes to the tenant'
      END AS reason
  ) a
  WHERE a.reason IS NOT NULL;

  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'tenant isolation incomplete -> %', bad;
  END IF;
END $guard_isolation$;

-- Views and matviews do NOT have RLS of their own. A view runs with its OWNER's
-- privileges unless created \`WITH (security_invoker = true)\`, and that default is
-- OFF. Measured: a plain view over \`conversations\` made tenant A see tenant B's
-- messages.
--
-- Matviews are worse: \`security_invoker\` does not apply to them at all, so the only
-- safe posture is withholding SELECT from the application role.
DO $guard_view$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, c.relname), ', ') INTO bad
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'v'
    AND has_table_privilege('quidchat_app', c.oid, 'SELECT')
    AND NOT coalesce(
      (SELECT option_value = 'true' FROM pg_options_to_table(c.reloptions)
       WHERE option_name = 'security_invoker'), false);
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'view without security_invoker=true but readable by quidchat_app -> %; the caller''s RLS does NOT apply there',
      bad;
  END IF;
END $guard_view$;

DO $guard_matview$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, c.relname), ', ') INTO bad
  FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND c.relkind = 'm'
    AND has_table_privilege('quidchat_app', c.oid, 'SELECT');
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'materialized view readable by quidchat_app -> %; matviews do not support security_invoker, so its SELECT privilege must be revoked',
      bad;
  END IF;
END $guard_matview$;

-- SECURITY DEFINER functions run as their creator, so they bypass RLS. And \`EXECUTE\`
-- is granted to PUBLIC by DEFAULT — without any explicit GRANT, the application role
-- can already call one. Measured: a dashboard function returned both tenants' message
-- counts.
--
-- \`current_tenant_id()\` itself is exempted: it genuinely needs to exist and it is
-- INVOKER.
DO $guard_secdef$
DECLARE bad text;
BEGIN
  SELECT string_agg(format('%s.%s', n.nspname, p.proname), ', ') INTO bad
  FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
    AND p.prosecdef
    AND has_function_privilege('quidchat_app', p.oid, 'EXECUTE');
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION
      'SECURITY DEFINER function executable by quidchat_app -> %; such functions bypass RLS',
      bad;
  END IF;
END $guard_secdef$;
`,
  },
  {
    name: "0004_message_skill.sql",
    sql: `-- Records which skill answered a message.
--
-- Without this the admin panel can show a transcript but not which skill produced it, so
-- an owner tuning routing rules has no way to tell whether a question went where they
-- intended. Routing is configurable, and configuration you cannot observe is guesswork.
--
-- Nullable on purpose: messages predating this column have no answer, and a tenant with
-- no skills configured routes to null and still answers. A NOT NULL column would have
-- forced a fake "default skill" into the schema to represent "no routing happened".
ALTER TABLE messages ADD COLUMN skill_id uuid;

-- Composite, carrying tenant_id, for the same reason every other foreign key here does:
-- foreign key checks bypass row security, so a plain reference to skills(id) would let a
-- message point at another tenant's skill. This makes that structurally impossible.
ALTER TABLE messages
  ADD CONSTRAINT messages_skill_fk
  FOREIGN KEY (tenant_id, skill_id) REFERENCES skills(tenant_id, id) ON DELETE SET NULL;

-- SET NULL rather than CASCADE: deleting a skill must not delete the conversations it
-- answered. The transcript is the business's record of what its customers were told.

CREATE INDEX messages_skill_idx ON messages (tenant_id, skill_id);
`,
  },
  {
    name: "0005_escalation_time.sql",
    sql: `-- Escalations need their own timestamp.
--
-- Ordering "newest first" previously fell back to the parent conversation's created_at,
-- which is exact per conversation and wrong across several escalations within one. The
-- escalations table is what an owner reads to decide what content to write next, and a
-- list in the wrong order sends them to the oldest gap first.
--
-- DEFAULT now() so existing rows get a value rather than sorting as null, and NOT NULL so
-- a future insert cannot omit it and reintroduce the same ambiguity.
ALTER TABLE escalations ADD COLUMN occurred_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX escalations_time_idx ON escalations (tenant_id, occurred_at DESC);
`,
  },
  {
    name: "0006_channel_configs.sql",
    sql: `-- Per-tenant channel credentials, so connecting WhatsApp or Telegram is something a business
-- does in the panel rather than something an operator does by editing the environment and
-- restarting the process.
--
-- Environment variables still work and still take part: they are the right shape for one
-- business running its own instance, and for a shared deployment where every tenant talks to
-- the same bot. What they cannot express is two businesses on one installation each using
-- their own WhatsApp number — which is the whole point of being multi-tenant.
CREATE TABLE channel_configs (
  tenant_id  uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  -- The adapter id, matching \`ChannelAdapter.id\` in @quidchat/channels. Constrained here
  -- rather than left open: a typo would produce a row that silently never matches a webhook,
  -- and a channel nobody can reach looks identical to one nobody configured.
  channel    text NOT NULL CHECK (channel IN ('telegram', 'whatsapp', 'waha', 'discord')),
  -- Disabled rather than deleted is the useful state: a business testing a channel wants to
  -- turn it off without re-entering its credentials.
  enabled    boolean NOT NULL DEFAULT true,
  -- The credentials, encrypted as one blob rather than column-per-field. Each channel needs a
  -- different set (a bot token here, a phone number id and an app secret there), and a table
  -- with a nullable column for every field of every channel is a table where nothing is
  -- required and nothing is validated. The application knows the shape; the database only has
  -- to keep it secret.
  --
  -- Encrypted with AES-256-GCM under QUIDCHAT_SECRET_KEY — see packages/server/src/secrets.ts.
  -- Plaintext here would mean a database backup, a read replica, or a stray SELECT hands over
  -- the ability to send messages as the business.
  secrets    text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, channel)
);

-- The PK already covers (tenant_id, channel); this is the lookup the webhook route does on
-- every inbound message, and it wants only the tenant.
CREATE INDEX channel_configs_tenant_idx ON channel_configs (tenant_id);

ALTER TABLE channel_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_configs FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON channel_configs
  USING (tenant_id = current_tenant_id())
  WITH CHECK (tenant_id = current_tenant_id());
`,
  },
]
